In [18]:
import numpy as np
import pandas as pd
import os

file_path = r'C:\Users\DELL\OneDrive\Documents\restaurant_customer_satisfaction.csv'

if os.path.exists(file_path):
    print("File exists. Attempting to read the file...")
    try:
        df = pd.read_csv(file_path)
        print("File read successfully:")
        print(df)
    except FileNotFoundError:
        print("File not found. Please check the path.")
    except pd.errors.EmptyDataError:
        print("No data. The file is empty.")
    except pd.errors.ParserError:
        print("Parsing error. The file might be corrupt or improperly formatted.")
    except Exception as e:
        print(f"An error occurred: {e}")
else:
    print("File does not exist. Please check the path.")
df = pd.read_csv(file_path)
# for x in df.index:
#  if df.loc[x, "Duration"] > 120:
#      df.drop(x, inplace = True)
df.head()

File exists. Attempting to read the file...
File read successfully:
      CustomerID  Age  Gender  Income VisitFrequency  AverageSpend  \
0            654   35    Male   83380         Weekly     27.829142
1            655   19    Male   43623         Rarely    115.408622
2            656   41  Female   83737         Weekly    106.693771
3            657   43    Male   96768         Rarely     43.508508
4            658   55  Female   67937        Monthly    148.084627
...          ...  ...     ...     ...            ...           ...
1495        2149   39    Male  114857        Monthly    163.015254
1496        2150   37  Female  133506         Weekly    190.991911
1497        2151   46    Male  119159        Monthly    150.088604
1498        2152   24    Male   27970         Weekly    196.363626
1499        2153   51    Male  148333         Weekly    171.119498

     PreferredCuisine TimeOfVisit  GroupSize DiningOccasion  MealType  \
0             Chinese   Breakfast          3       Business  Takeaway
1            American      Dinner          1         Casual   Dine-in
2            American      Dinner          6    Celebration   Dine-in
3              Indian       Lunch          1    Celebration   Dine-in
4             Chinese   Breakfast          1       Business  Takeaway
...               ...         ...        ...            ...       ...
1495         American       Lunch          2       Business   Dine-in
1496          Italian       Lunch          4         Casual  Takeaway
1497         American       Lunch          4         Casual   Dine-in
1498          Italian      Dinner          6         Casual   Dine-in
1499          Chinese   Breakfast          4         Casual   Dine-in

      OnlineReservation  DeliveryOrder  LoyaltyProgramMember   WaitTime  \
0                     0              1                     1  43.523929
1                     0              0                     0  57.524294
2                     0              1                     0  48.682623
3                     0              0                     0   7.552993
4                     0              0                     1  37.789041
...                 ...            ...                   ...        ...
1495                  0              1                     1   7.206275
1496                  0              0                     0  37.863952
1497                  0              1                     0   3.925785
1498                  1              1                     0  24.228038
1499                  1              1                     1  39.402163

      ServiceRating  FoodRating  AmbianceRating  HighSatisfaction
0                 2           5               4                 0
1                 5           5               3                 0
2                 3           4               5                 0
3                 4           5               1                 0
4                 2           3               5                 0
...             ...         ...             ...               ...
1495              1           2               1                 0
1496              5           2               2                 0
1497              3           3               3                 1
1498              2           2               4                 1
1499              4           5               4                 1

[1500 rows x 19 columns]

,CustomerID,Age,Gender,Income,VisitFrequency,AverageSpend,PreferredCuisine,TimeOfVisit,GroupSize,DiningOccasion,MealType,OnlineReservation,DeliveryOrder,LoyaltyProgramMember,WaitTime,ServiceRating,FoodRating,AmbianceRating,HighSatisfaction
0,654,35,Male,83380,Weekly,27.829142,Chinese,Breakfast,3,Business,Takeaway,0,1,1,43.523929,2,5,4,0
1,655,19,Male,43623,Rarely,115.408622,American,Dinner,1,Casual,Dine-in,0,0,0,57.524294,5,5,3,0
2,656,41,Female,83737,Weekly,106.693771,American,Dinner,6,Celebration,Dine-in,0,1,0,48.682623,3,4,5,0
3,657,43,Male,96768,Rarely,43.508508,Indian,Lunch,1,Celebration,Dine-in,0,0,0,7.552993,4,5,1,0
4,658,55,Female,67937,Monthly,148.084627,Chinese,Breakfast,1,Business,Takeaway,0,0,1,37.789041,2,3,5,0

In [19]:
df_1 = pd.DataFrame({
 'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
 'subject_id':['sub1','sub2','sub4','sub6','sub5'],
 'Marks_scored':[98,90,87,69,78]},
 index=[1,2,3,4,5])
df_2 = pd.DataFrame({
 'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
 'subject_id':['sub2','sub4','sub3','sub6','sub5'],
 'Marks_scored':[89,80,79,97,88]},
 index=[1,2,3,4,5])
print(pd.concat([df_1,df_2], ignore_index=True))

     Name subject_id  Marks_scored
0    Alex       sub1            98
1     Amy       sub2            90
2   Allen       sub4            87
3   Alice       sub6            69
4  Ayoung       sub5            78
5   Billy       sub2            89
6   Brian       sub4            80
7    Bran       sub3            79
8   Bryce       sub6            97
9   Betty       sub5            88

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [9]:
df.isna().sum()

CustomerID              0
Age                     0
Gender                  0
Income                  0
VisitFrequency          0
AverageSpend            0
PreferredCuisine        0
TimeOfVisit             0
GroupSize               0
DiningOccasion          0
MealType                0
OnlineReservation       0
DeliveryOrder           0
LoyaltyProgramMember    0
WaitTime                0
ServiceRating           0
FoodRating              0
AmbianceRating          0
HighSatisfaction        0
dtype: int64

In [10]:
# Merging in pandas
df1 = pd.DataFrame({
 'id':[1,2,3,4,5],
 'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
 'subject_id':['sub1','sub2','sub4','sub6','sub5']})
df2 = pd.DataFrame(
 {'id':[1,2,3,4,5],
 'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
 'subject_id':['sub2','sub4','sub3','sub6','sub5']})
pd.merge(df1, df2, on="id")

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5

In [15]:
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])
print(s.str.lower())
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])
print(s.str.upper())
s = pd.Series(['Tom', 'William Rick ', 'John ', 'Alber@t ', np.nan, '1234','SteveSmith'])
print(s.str.strip())
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])
print(s.str.startswith('T'))
s = pd.Series(['Tom', 'William Rick', 'John', 'Alber@t', np.nan, '1234','SteveSmith'])
print(s.str.endswith('h'))

0             tom
1    william rick
2            john
3         alber@t
4             NaN
5            1234
6      stevesmith
dtype: object
0             TOM
1    WILLIAM RICK
2            JOHN
3         ALBER@T
4             NaN
5            1234
6      STEVESMITH
dtype: object
0             Tom
1    William Rick
2            John
3         Alber@t
4             NaN
5            1234
6      SteveSmith
dtype: object
0     True
1    False
2    False
3    False
4      NaN
5    False
6    False
dtype: object
0    False
1    False
2    False
3    False
4      NaN
5    False
6     True
dtype: object

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [24]:
# import pandas as pd
# import numpy as np
df4 = pd.DataFrame(np.random.rand(10,4),columns=['a','b','c','d'])
df4.plot.bar()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [26]:
df2 = df[750]
df2.head()

KeyError: 750